name: Staging deployment

on: 
  pull_request:
    types: [labeled]

env:
  DOCKER_IMAGE_NAME: mehrotra-prateek-azure-ttt
  IMAGE_REGISTRY_URL: docker.pkg.github.com
  #################################################
  ### USER PROVIDED VALUES ARE REQUIRED BELOW   ###
  #################################################
  #################################################
  ### REPLACE USERNAME WITH GH USERNAME         ###
  AZURE_WEBAPP_NAME: mehrotra-prateek-ttt-app
  #################################################

jobs:
  build:
    runs-on: ubunutu-latest
    
    if: contains(github.event.pull_request.labels.*.name, 'stage')
